  export const ThemeColors = [
    {classname: 'red', dispname: 'Red'},
    {classname: 'pink', dispname: 'Pink'},
    {classname: 'purple', dispname: 'Purple'},
    {classname: 'deep-purple', dispname: 'Deep Purple'},
    {classname: 'indigo', dispname: 'Indigo'},
    {classname: 'blue', dispname: 'Blue'},
    {classname: 'light-blue', dispname: 'Light Blue'},
    {classname: 'cyan', dispname: 'Cyan'},
    {classname: 'teal', dispname: 'Teal'},
    {classname: 'green', dispname: 'Green'},
    {classname: 'light-green', dispname: 'Light Green'},
    {classname: 'lime', dispname: 'Lime'},
    {classname: 'yellow', dispname: 'Yellow'},
    {classname: 'amber', dispname: 'Amber'},
    {classname: 'orange', dispname: 'Orange'},
    {classname: 'deep-orange', dispname: 'Deep Orange'},
    {classname: 'brown', dispname: 'brown'},
    {classname: 'grey', dispname: 'Grey'},
    {classname: 'blue-grey', dispname: 'Blue Grey'},
    {classname: 'black', dispname: 'Black'},
  ]
